### ISSUE TITLE
切换导图后，图片无法显示。

### ISSUE THREAD

**Issue by Kaine233** [vipzhicheng/logseq-plugin-mark-map#1]
![image](https://user-images.githubusercontent.com/87978896/127474341-92bd413d-6589-4dc7-985c-5659d5f33c20.png)
![image](https://user-images.githubusercontent.com/87978896/127474260-36256f0e-abcd-493e-a704-c05064e90c9e.png)
图片用的阿里云图床。
Logseq版本：0.2.10
logseq-plugin-mark-map-0.0.1

**Comment by vipzhicheng** [comment]
这个插件是对Markmap的封装，Markmap项目目前就是不支持图片的，等什么时候支持了，我这边也会更新。

或者能找到更好的导图展示开源项目，也可以研究再做一个插件。
