### ISSUE TITLE
Can't be used

### ISSUE THREAD

**Issue by msjsc001** [vipzhicheng/logseq-plugin-mark-map#11]
![image](https://user-images.githubusercontent.com/93178788/138815836-21285ab8-b92b-4a32-9487-c5226308dadc.png)
My operating system is Win10
![20210606180518](https://user-images.githubusercontent.com/93178788/138997697-a2c3c668-5f6e-4ec8-86d4-c280a1b2c762.gif)
Click on the upper right corner icon without any reactions

**Comment by vipzhicheng** [comment]
1. Seems you have two versions at the same time, Please uninstall one of them.
2. Try open devtools to see if it have any warnings or errors.
3. Do you install them by using Logseq marketplace, if not, please give it a try.

Basically, I have tested the plugin on Mac and Windows 10.

**Comment by msjsc001** [comment]
After uninstalling one of the plugins, the problem is solved. Thank you!
