### ISSUE TITLE
 The resolution of the exported picture is not high enough

### ISSUE THREAD

**Issue by tianyalang** [vipzhicheng/logseq-plugin-mark-map#13]
如果内容较多的话，导出的图片清晰度不太够，有些字会看不清楚

![1](https://hezudao-picturebed.oss-cn-beijing.aliyuncs.com/img/面壁计划.png)

**Comment by vipzhicheng** [comment]
内容太多的话，字就会越来越小，建议折叠起来一部分，看这个图，主要还是高亮那里不清楚，可以试试按 `r` 换个背景色试试。

**Comment by tianyalang** [comment]
> 内容太多的话，字就会越来越小，建议折叠起来一部分，看这个图，主要还是高亮那里不清楚，可以试试按 `r` 换个背景色试试。

好的，谢谢
