### ISSUE TITLE
local image not shown in mind map mode

### ISSUE THREAD

**Issue by meilier** [vipzhicheng/logseq-plugin-mark-map#14]
I'm using mac os logseq client. Try some examples with logseq, and glad to find a mind map plugin. But upload assets of images can not be shown in mind map mode, remote images with url are fine.  

Its a permission problem? But normal doc is fine with images. Since I'm not familiar with js, need some help here. Thanks

**Comment by vipzhicheng** [comment]
I use mac also, and I tried on my mac, local image can show correctly, but mindmap plugin can not show image directly, but convert it to an image icon, after click it, you image will popup.

If you can see the image icon,but can not see your image popup, you can try to open `Developer mode` by clicking `alt+cmd+i` to Console tab to see if it has any error message.

**Comment by vipzhicheng** [comment]
Will close it, if needed please reopen.
