### ISSUE TITLE
Backlinks are not displayed

### ISSUE THREAD

**Issue by almereyda** [vipzhicheng/logseq-plugin-mark-map#16]
A local nodes backlinks provide suitable insight into references throughout the graph.

We could imagine to visually investigate those with activating a certain property of this plugin, and them being rendered as input flows to the central node.

Accessing this also allowed for a kind of Sankey, or two-sided flow diagram layout of the input data.

**Comment by vipzhicheng** [comment]
Sounds like this should be a brand new plugin to do.

**Comment by almereyda** [comment]
Yes, probably the two directions of connections (incoming, outcoming) are two different qualities of a node and can as such not be combined in a single visual representation.
