### ISSUE TITLE
Apply the view mindmap to a block ?

### ISSUE THREAD

**Issue by bepolymathe** [vipzhicheng/logseq-plugin-mark-map#17]
Hi @vipzhicheng 

Thanks for this plugin and happy new year. 
This is not a bug report but a feature request. When taking notes in the diary, there are often different levels of bulleted lists. When you want to focus on one of them, you just have to click on it to have a didactic view at this level only. It would be ideal to be able to apply the mindmap view at this level... Currently it applies to the whole page. 
What do you think of this idea ?

**Comment by vipzhicheng** [comment]
Recently I am also thinking about this kind of idea, but have no time to dive into it. Before I work out this feature, you can use shortcuts to focus what you want by pressing `.` shortcut to focus, `j`, `k` to move up and down.

**Comment by vipzhicheng** [comment]
Please upgrade the plugin to the newest version, this feature has been added now.

**Comment by bepolymathe** [comment]
> Please upgrade the plugin to the newest version, this feature has been added now.

That's great ! Thanks you !

**Comment by happy15** [comment]
markmap on block only shows current block but not any child of current block. I triggered markmap on block from the right click menu on block, or ctrl-m ctrl-m from block page. 

logseq 0.5.9
markmap plugin 0.1.7

**Comment by bepolymathe** [comment]
Indeed. I saw this too in recent past....

**Comment by vipzhicheng** [comment]
I already noticed Logseq API changed a little bit, will release fix soon.

**Comment by vipzhicheng** [comment]
@bepolymathe @happy15 new version released, please have a try.

**Comment by happy15** [comment]
> @bepolymathe @happy15 new version released, please have a try.

it’s fixed in my case. great job and thanks.

**Comment by bepolymathe** [comment]
Sorry but not in my case. I have a blank page...

**Comment by vipzhicheng** [comment]
@bepolymathe did u use the latest version Logseq? Can you please provide some example blocks data or screenshots? Or help me to check what Chrome console output.

**Comment by bepolymathe** [comment]
Hi @vipzhicheng 

Sorry, the plugin was not well update :thinking: 
It works.
