### ISSUE TITLE
如果内容非常多,导出来的图片文字很模糊,看不清

### ISSUE THREAD

**Issue by jiagoumengxiang** [vipzhicheng/logseq-plugin-mark-map#18]

**Comment by vipzhicheng** [comment]
这个暂时没有什么好办法，因为只能导出视窗那么大，不是像网页那样可以滚动很长。内容越多字越小

**Comment by vipzhicheng** [comment]
我对导出图片做了一点修改，现在可以导出高清图片，但需要按照指定的步骤进行操作。请看README。

**Comment by WaytrueDeng** [comment]
> 我对导出图片做了一点修改，现在可以导出高清图片，但需要按照指定的步骤进行操作。请看README。

请问作者大佬能不能添加导出为svg啊这样应该就不怕这个问题了

**Comment by vipzhicheng** [comment]
哈，那还得再研究研究
