### ISSUE TITLE
pdf item showing bug

### ISSUE THREAD

**Issue by clark-cui** [vipzhicheng/logseq-plugin-mark-map#19]
### describtion:
When the content has pdf item, click it will make a loading and then nothing happen.
### gif:

![animation](https://user-images.githubusercontent.com/46164858/148492778-fae47e1a-c066-4ad5-94bf-52388c2c1c64.gif)

### reporduce: 

1. upload a pdf.
2. click mark-map button to show mind map.
3. click pdf item

**Comment by clark-cui** [comment]
I just test  a local image, it has same issue like this.
I notice this comment , so is this a known issue on windows?
https://github.com/vipzhicheng/logseq-plugin-mark-map/blob/7a75451b8bce031e8d26f9ffd2336a9d24002118/src/main.ts#L456

**Comment by vipzhicheng** [comment]
Ah, that's a rare case, I even did not think about it, I will try to reproduce it on Mac to see what happened, by the way, if it's pdf link, the best reaction would be close the mindmap and open the pdf? I don't think I could do it from a plugin.

**Comment by vipzhicheng** [comment]
@clark-cui FYI in next release it will be fixed, but only make it not clickable on markmap
