### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by red-co** [vipzhicheng/logseq-plugin-mark-map#27]
1. 限制宽度，
2. 兼容无序列表，
- 现在的情况，
<img width="731" alt="image" src="https://user-images.githubusercontent.com/75922982/165717294-0f519457-5b1f-4afb-8f96-fda3e8241925.png">
- 希望得到的效果
  - 

https://user-images.githubusercontent.com/75922982/165717558-ab12e41e-1ace-43e0-8703-675974191d30.mp4

**Comment by vipzhicheng** [comment]
兼容宽度的功能已经加上了
