### ISSUE TITLE
Admonitions looks like #BEGIN_QUOTE/EXAMPLE/WARNING etc. in markmaps.  Is there any solution for that?

### ISSUE THREAD

**Issue by sredine** [vipzhicheng/logseq-plugin-mark-map#28]
<img width="632" alt="Ekran Resmi 2022-05-17 20 33 00" src="https://user-images.githubusercontent.com/30051527/168876289-f9b69db7-1382-4adc-86ae-81436b7dbfc0.png">
I want to see my admonition blocks in markmaps. Is it possible to fix this issue in later versions of the plugin?

**Comment by vipzhicheng** [comment]
a new version was released, please update to see if it solves your situation.

**Comment by sredine** [comment]
It is solved, thanks a lot
