### ISSUE TITLE
Markmap doesnt fit to canvas while exporting png 

### ISSUE THREAD

**Issue by sredine** [vipzhicheng/logseq-plugin-mark-map#29]
I have complex and pretty big vertical markmaps. when i try to export them to png it doesnt fit to canvas i guess and exported png is high quality but doesnt contain all of the markmap. Is there any solution for this problem? Am i doing something wrong or does it need an update?

**Comment by vipzhicheng** [comment]
You can try to export to an SVG image, open the SVG in a browser, and try to screenshot the whole page. 

Another solution would be hard to operate, there is a tip in the project README to talk about how to catch a high-quality png.
