### ISSUE TITLE
Org syntax

### ISSUE THREAD

**Issue by c6p** [vipzhicheng/logseq-plugin-mark-map#3]
Is it possible to parse org syntax for links, references, and text decorations?

**Comment by vipzhicheng** [comment]
I am not familiar with org syntax, can you please provide a demo doc to show org formats?

And for links and references, it's just text on mindmap, and can not jump internally.

**Comment by c6p** [comment]
I see. What I mean parsing links etc. Logseq help page lists syntax differences.
![image](https://user-images.githubusercontent.com/80478/130652377-713dbbe8-31b5-4a04-b8f1-3aab8da26463.png)

As you can see below, output is not pretty, especially with long URIs.
![image](https://user-images.githubusercontent.com/80478/130652917-49763d14-19e6-4499-b2a3-5a770fd5b4cc.png)

I have made a request in plugin development forum here. Could you vote? If logseq expose a conversion function, not every plugin developer would need to re-implement their own parsers.
 https://discuss.logseq.com/t/org-to-markdown-converter-and-create-pages-in-non-preferred-format/2202

**Comment by vipzhicheng** [comment]
I just released a version of this request, please have a try.

It's not perfect, but hopefully, it can solve your problem.

**Comment by c6p** [comment]
Thank you for your time. It is great.

As you can see below; bold, strike-through, highlight and local links does not work. Interesting bit is, internal links do not render even when without wiki syntax, when they have the same syntax as an external link. 

    - **Bold**
    - *Italics*
    - ~~Strikethrough~~
    - ^^Highlight^^
    - $$E = mc^2$$ - `Code`
    -
      ``` clojure
    (println "Hello world!")
      ```
    - [[https://www.example.com][label]]
    - [[2021-09-12 Sunday]]
    - [[2021-09-12 Sunday][2021-09-12 Sunday]]

![image](https://user-images.githubusercontent.com/80478/132983138-0d1c8c75-8843-4e0c-af80-4d792ff2aa74.png)

**Comment by vipzhicheng** [comment]
1. Actually, bold has been working.
2. Strikethrough will be fixed at the next release.
3. highlight will not be supported because of upstream markmap package not support it.
4. internal link is not supported is a known issue. The reason is like 3. But I will work on this issue later to try to fix it.

**Comment by vipzhicheng** [comment]
New version released, please have a try.

**Comment by vipzhicheng** [comment]
Please compare with/without *. On my laptop, I can see the difference, so I think it works.

![image](https://user-images.githubusercontent.com/1209538/134442660-da1ed57b-a1f1-4250-adb6-838fbf5debb8.png)

**Comment by c6p** [comment]
You are right, the problem is font. I should have checked HTML first.

Thank you, again, for org parser and this plugin. 💯
