### ISSUE TITLE
[Request] Uniform braches

### ISSUE THREAD

**Issue by stackingflow** [vipzhicheng/logseq-plugin-mark-map#32]
Can you please add an option to make the branches look uniform and squary something like this:
![Screenshot 2022-05-26 at 7 06 15 PM](https://user-images.githubusercontent.com/47140829/170498554-7562c41d-42c9-440f-bac6-914ed8744dec.png)

**Comment by vipzhicheng** [comment]
I remember the render only supports an option to disable color, but can not change others of branches.
