### ISSUE TITLE
大神，可以帮帮我看看怎么安装这个插件吗？在线安装不了，离线安装使用不了，不知道哪里做错了555

### ISSUE THREAD

**Issue by KK-3458** [vipzhicheng/logseq-plugin-mark-map#34]
新新手，轻拍
在线插件市场可以打开看到插件
但是点击安装就会出现这样的提示错误
<img width="361" alt="image" src="https://user-images.githubusercontent.com/66560506/171983474-999de349-13b9-4e19-a2fe-ef6367c08858.png">

如果是去github里下载然后手动载入，就会显示这样，然后在页面那里也没有什么图标或者选项可以转换成思维导图。
![image](https://user-images.githubusercontent.com/66560506/171983541-b2b58fde-7851-438e-a80a-939f0800ce86.png)
【不过不知道自己操作的对不对，自己下载的是下面图中框出来的两个（两个都试过并解压过）】

然后打开插件的配置项，得到的是这样的结果
![image](https://user-images.githubusercontent.com/66560506/171983545-268bc140-9400-4061-931a-bbd62e389c5a.png)

不知道自己是哪一步做错了，为什么安装/使用不了插件呢555

**Comment by vipzhicheng** [comment]
如果你有VPN，可以配置一下代理，Logseq是支持的，如果是手动安装，确保高级设置里开启了开发者模式和插件系统，然后用cmd/ctrl+r重新刷新一下窗口，理论上就可以了，如果不行就再刷新一次。
