### ISSUE TITLE
Highlight is not rendered

### ISSUE THREAD

**Issue by Xemnas0** [vipzhicheng/logseq-plugin-mark-map#35]
The "^^" notation for highlighting text does not get rendered and sometimes lifts the text up.

Would it be possible to have it highlighted in the map?

Example below
![image](https://user-images.githubusercontent.com/26822543/173658456-ee82f83b-f1f1-4d10-a106-c8b3c28a2869.png)

**Comment by vipzhicheng** [comment]
The syntax of highlights in mindmap render is `==`, I think I can replace it for compatibility. Please wait for the next release.
