### ISSUE TITLE
SVG 文件格式错误,并且svg只能显示生成svg的当前层级,而不是全部.如果缩放到全部overview的话svg又太小而且还不能缩放,失去了矢量图的优势

### ISSUE THREAD

**Issue by WaytrueDeng** [vipzhicheng/logseq-plugin-mark-map#36]
<img width="1691" alt="image" src="https://user-images.githubusercontent.com/61548208/174929267-52350014-b13f-4b09-b2c7-223ef658833f.png">

**Comment by vipzhicheng** [comment]
可以发个有问题的svg当例子嘛，我用来测试的用例是能打开的。

![image](https://user-images.githubusercontent.com/1209538/177259372-fdb04d57-79e8-44c9-b3ed-6e1aa7fa0d30.png)

**Comment by m3lab-zzl** [comment]
@vipzhicheng 我这有一个例子，可能是因为有图片的原因

![image](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/102862066/ded3c770-f859-4fff-a948-de9e2620ba09)

![fish-shell.svg](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/102862066/355de136-a1b5-448b-8e9d-b3c13d76144d)

[fish-shell.md](https://github.com/user-attachments/files/15864678/fish-shell.md)

插件的设置如下：

![image](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/102862066/ffac1430-9139-48a2-8079-5685a7c8fdd4)

![image](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/102862066/755ef053-7918-414e-9e73-184b4b394443)

感谢作者的开发，这个插件导出PNG图片还是很好用的，一直在用。但是前天想打开SVG的时候才发现有问题，所以找到这个议题的。

**Comment by vipzhicheng** [comment]
我修了这个问题，麻烦升级测试一下。

**Comment by m3lab-zzl** [comment]
已升级测试通过，感谢

**Comment by m3lab-zzl** [comment]
@vipzhicheng svg虽然支持图片了，但是是否支持超链接或者其他更复杂的情况？

我这有一个测试文档，转成svg后无法用Firefox直接打开
![image](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/102862066/c6317fd4-5e9b-4c28-a335-e26b561875e6)

Windows quicklook倒是可以看到轮廓
![image](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/102862066/0c03528b-783b-4a62-aa43-3c4888554ecd)

导出之前查看是正常的
![image](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/102862066/bea3f5d0-16a4-4fbf-99ed-74d7e68f5723)

测试的 markdown 文件：
[test.md](https://github.com/user-attachments/files/15916874/test.md)

**Comment by vipzhicheng** [comment]
我又发布了一个版本，试试看是否解决了这个问题。

**Comment by m3lab-zzl** [comment]
现在文字是正常的，但是图片好像缺失了？
![image](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/102862066/e2d3afaf-bfc4-4c08-b9c1-b470b334fe6c)


上一个小版本，图片我记得是有缩略图，而且可以点开看的。现在不渲染了，Firefox点开也说协议不支持。
![image](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/102862066/de1da5bb-6dc8-48c7-bc3e-1890f586f1bf)

![image](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/102862066/a74f05b8-d3b1-48d1-87f9-341cc0ac4cee)

**Comment by vipzhicheng** [comment]
我用上一个测试文档是没问题的，可以发一下这次的文档我来试试

![image](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/1209538/0cf54659-9664-4ea2-973a-437c9990d403)

**Comment by m3lab-zzl** [comment]
测试文档还是那个 test.md 没有改变

**Comment by vipzhicheng** [comment]
看我上面的截图，就是在firefox截的图，无法重现您的问题

**Comment by m3lab-zzl** [comment]
可能是操作系统的问题，我在osx上测试通过，在win10上不行，这是两个svg文件

[test_win10.svg](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/102862066/78891ea7-a77e-4519-88d1-6efb4652adfb)

[test_osx.svg](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/102862066/37906dfd-cd2a-4aad-a926-41d170b9312f)

**Comment by vipzhicheng** [comment]
又发了一版，尝试修复这个问题，试试看，：）

**Comment by DeeliN221** [comment]
测试通过，换了其他几个更复杂的笔记，也没发现问题，应该是可用了。666 👍
