### ISSUE TITLE
需求：为map节点添加链接，能够跳转到对应的block

### ISSUE THREAD

**Issue by forvenus** [vipzhicheng/logseq-plugin-mark-map#38]
您好，首先感谢开发这个插件，效果很好！
我在日常使用中，感觉如果能添加上：节点跳转到block的功能，将更加方便！

**Comment by vipzhicheng** [comment]
这个是什么意思呢？点击以后是关闭导图进入到对应的block还是以那个block为中心，重新渲染导图

**Comment by sbwcwso** [comment]
> 这个是什么意思呢？点击以后是关闭导图进入到对应的block还是以那个block为中心，重新渲染导图

我觉得关闭导图定位到相应的 block，但是保持在当前的页面。这样可以方便的使用思维导图进行定位，比较方便。

**Comment by vipzhicheng** [comment]
This feature has been implemented, please upgrade. It's disabled by default, please find it on the plugin's settings page.
