### ISSUE TITLE
有超链接的bug

### ISSUE THREAD

**Issue by clark-cui** [vipzhicheng/logseq-plugin-mark-map#4]
页面内容里如果有超链接block，点击后不会在浏览器打开，而是在Logseq中打开，按ESC/Q不能退出，导致流程卡死
比如
[vivo 衡量前端性能](https://mp.weixin.qq.com/s/6QOs0MqPqR2koKek-dMZbw)

**Comment by vipzhicheng** [comment]
这个问题会在下一个版本中修复，会对所有链接默认新窗口打开

**Comment by vipzhicheng** [comment]
New version released, please have a try.
