### ISSUE TITLE
Can you please cleanup {{cloze}} stuff?

### ISSUE THREAD

**Issue by working-name** [vipzhicheng/logseq-plugin-mark-map#40]
Hello!

I was wondering if you have a quick way to clean up {{cloze ...}} blocks. For example, if you were to go the regex route: https://regex101.com/r/8HDVtS/1 ( [code generator](https://regex101.com/r/8HDVtS/1/codegen?language=javascript) )

<img width="899" alt="Screen Shot 2022-08-07 at 7 06 33 AM" src="https://user-images.githubusercontent.com/16505052/183289690-9adda4d3-8379-43ba-aca9-942187dddd45.png">

Thank you!

**Comment by vipzhicheng** [comment]
You mean remove `{{cloze` but keep `skin, fascia....`?

**Comment by working-name** [comment]
Yes sir

**Comment by vipzhicheng** [comment]
Please upgrade and then take a look~
