### ISSUE TITLE
Keyboard shortcut conflicts with Move Block plugin

### ISSUE THREAD

**Issue by almereyda** [vipzhicheng/logseq-plugin-mark-map#47]
When starting LogSeq, an error is thrown that reads:

> :plugin.logseq-mark-map/mark-map-open-full ctrl+shift+m ctrl+shift+m Keyboard shortcut conflicts with existing shortcut: plugin.logseq-copy-ref-to-journal/move-block

I don't know which one should be given precedence here, or how to configure the plugin.

---

This is the mirror version of

- https://github.com/vipzhicheng/logseq-plugin-move-block/issues/11

**Comment by vipzhicheng** [comment]
Yes, I guest you are using Windows. I give `cmd+shift+m` to Move Block by default but it's `ctrl+shift+m` on Windows which 
is conflict with Markmap. I will give another default bind to Mark Map which would be `ctrl+alt+shift+m`. 

And you can edit plugin settings file of any plugin to change the binding manually before that.

Most of time I do not use shortcuts to trigger Mark Map actually.

**Comment by vipzhicheng** [comment]
For now, it's `ctrl+alt+shift+m`.
