### ISSUE TITLE
Displayed math only shows up from the 7th level

### ISSUE THREAD

**Issue by fkguo** [vipzhicheng/logseq-plugin-mark-map#49]
Hello,

I find that the displayed math formulas show up in the map only from the 7th level, see the attached image:
![image](https://user-images.githubusercontent.com/62633089/199009948-53b92a26-42c8-4c5b-bd05-9d75a4849b85.png)
where every "test" is followed by a hard line break and then the same displayed formula.

Is it possible to let the formulas show up at all levels?

Thank you!

**Comment by vipzhicheng** [comment]
Please upgrade, it maybe has been fixed now.

**Comment by fkguo** [comment]
Thanks! Now the math expressions between `$$ $$` show up at all levels without truncation. Can the expressions in math environments like `\begin{equation} ... \end{equation}`, `\begin{align} ... \end{align}` also be rendered?

**Comment by vipzhicheng** [comment]
I'm afraid not. The upstream lib does not support this syntax. Seems Logseq does not support it either.

**Comment by fkguo** [comment]
Thanks. It is supported by LogSeq.

**Comment by vipzhicheng** [comment]
Can you please give me a raw example? Then I can paste it to Logseq to see what it looks like.

**Comment by fkguo** [comment]
for instance, you can put 
```
\begin{equation}
f(z)=\sum_{n=0}^{\infty} a_n(z-z_0)^n ,
\end{equation}  
```
into logseq. It is properly rendered.

**Comment by vipzhicheng** [comment]
Yes, it's rendered. I am not familiar with this syntax. And upstream lib does not support it for sure. What I can do is to replace something with `$$`.  e.g.

`\begin{equation}` to `$$`
`\end{equation}` to `$$`

I don't know if it is correct and if it is enough. I need your help to point me out.

**Comment by vipzhicheng** [comment]
Seems the last two are also not supported.
