### ISSUE TITLE
对于引用块的支持问题

### ISSUE THREAD

**Issue by xlangzhong** [vipzhicheng/logseq-plugin-mark-map#5]
如图所示，引用块貌似不会在导图上显示出所阴阳内容，而是出现引用代码
![image](https://user-images.githubusercontent.com/71161243/133960259-8e7cfb95-1849-4c6f-b4b6-4925e9c2351b.png)

**Comment by vipzhicheng** [comment]
发了新版，解决了这个问题以及类似问题，试试看。
