### ISSUE TITLE
Render tags

### ISSUE THREAD

**Issue by balta2ar** [vipzhicheng/logseq-plugin-mark-map#50]
Not sure if this is an upstream lib issue, but when I use `[[tags]]`, they are not rendered perfectly:
![image](https://user-images.githubusercontent.com/340676/200171970-52df903f-7bbe-43e4-b380-95c1a3c492dd.png)
![image](https://user-images.githubusercontent.com/340676/200172001-780f8156-7e8d-4589-b5c7-07b9b7b0b2c7.png)

**Comment by vipzhicheng** [comment]
What original tag text is? `[better text]([[tag]])` this way?

**Comment by balta2ar** [comment]
in raw text I have this:
```
- [[request batch]]  
	- batch N request with a timeout  
```

**Comment by vipzhicheng** [comment]
> in raw text I have this:
> 
> ```
> - [[request batch]]  
> 	- batch N request with a timeout  
> ```

This can not be reproduced. Please confirm the issue page use the same syntax as you provided.

**Comment by balta2ar** [comment]
Yes, I confirm that. I also noticed that it works when tag contains only one word (some incomplete regexp?), e.g. have a look at "lease":
![image](https://user-images.githubusercontent.com/340676/201584750-d3fadbd4-c24c-45ea-9251-dca376f33f95.png)
[distributed systems patterns.md](https://github.com/vipzhicheng/logseq-plugin-mark-map/files/9999962/distributed.systems.patterns.md)
I attached the whole file. In this case it's markdown, but I also use org in other files.

**Comment by vipzhicheng** [comment]
That's weird. Mine is correct. So what is your environment? Mine is MacOS,Logseq  0.8.10.

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/1209538/201812140-3105a3a7-219a-4957-b789-77dff1942e3c.png">

**Comment by balta2ar** [comment]
Manjaro Linux, logseq 0.8.10.

I stared using logseq with default settings (markdown) and created some articles in markdown, but then I changed settings to org, so now I have some articles in MD and some in ORG.

**Comment by vipzhicheng** [comment]
I can not reproduce it with first markdown format then org format process on Mac.

And for me, I don't have a Manjaro env for now. So maybe it will take some time to be solved.
