### ISSUE TITLE
An option to disable repositioning/change of focus on expand/collapse

### ISSUE THREAD

**Issue by balta2ar** [vipzhicheng/logseq-plugin-mark-map#51]
Whenever I collapse/expand a node, the UI automatically moves the "camera" and repositions the view. This gets very annoying when I zoomed in into a particular part of a tree and I'd like to keep that zoom level as focus, and expand/collapse at the same time, but currently I'm thrown back to some default view every time.

**Comment by vipzhicheng** [comment]
Please upgrade to the latest version. I added an option to control that. Please take a look.

**Comment by balta2ar** [comment]
Thank you! :heart:  This is very useful for me when I use mindmaps as a visual guide when I give a presentation.
