### ISSUE TITLE
[feature-request] double click to go to block

### ISSUE THREAD

**Issue by danilofaria** [vipzhicheng/logseq-plugin-mark-map#52]
The killer feature of this plugin would be to allow editing the block contents directly on the map view. However, I do realize this is not possible due to the limitations of mark-map itself.

However, the next-best feature would be to double-click on a map node and then it takes you back to the block view on that specific block so you can edit it. Sometimes when viewing a large map, one may wish to edit a specific node, so this feature would be awesome.

**Comment by vipzhicheng** [comment]
For now, I had added an option to add an anchor to each node, then when you click the green icon on the left, you will be taken to that submap, and Logseq do that also. Then you only need to click `q`, then you can edit it on Logseq.

Speaking of editing block on Markmap, I also have a plan. ut you are right that's not an easy mission.

**Comment by danilofaria** [comment]
Hey @vipzhicheng thanks for the reply. I looked through the instructions but could not find out how to set up the anchor you mentioned, I also did not see this green icon. Can you give me some pointers?

> Speaking of editing block on Markmap, I also have a plan. ut you are right that's not an easy mission

Ooh, that's exciting!

**Comment by vipzhicheng** [comment]
First, you need to upgrade to the latest version. then go to the settings page.

<img width="947" alt="image" src="https://user-images.githubusercontent.com/1209538/201248657-d3652d83-5c48-422b-847b-42b71de568e4.png">

**Comment by danilofaria** [comment]
awesome, thanks for the pointer. 
BTW, on a related note: when I do focus on a block in Logseq, the markmap graph mode icon disappears. I can only see that button when I am on a page. Would be nice to enter markmap graph mode from a block page too 🙂

**Comment by vipzhicheng** [comment]
It depends on Logseq rules. But I added a shortcut: double `mod+m` to trigger markmap on a block page. You can have a try.
