### ISSUE TITLE
[bug] Reference tag not displayed as expected with "Node Anchor" = off

### ISSUE THREAD

**Issue by emms007** [vipzhicheng/logseq-plugin-mark-map#54]
Hello,

Thanks for the great plugin.
I think I went through a bug when playing with the plugin for my first time on a page that had references "[^1]" and "[^1]:"
It does not occur with I activate "Node Anchor".

I am attaching the md demo file.
![image](https://user-images.githubusercontent.com/171033/204769556-5f3a49f1-2962-417d-ba9f-a6d0f302b5db.png)
[test%2Fmindmap.md](https://github.com/vipzhicheng/logseq-plugin-mark-map/files/10122071/test.2Fmindmap.md)

**Comment by vipzhicheng** [comment]
<img width="1608" alt="image" src="https://user-images.githubusercontent.com/1209538/204971066-7f5a372b-e262-400d-8168-9f29d901a655.png">

This is what I see, seems correct. So what's your environment?

**Comment by emms007** [comment]
From your screenshot you are using "anchor" mode. Try to set it off and you'll see the problem.

**Comment by vipzhicheng** [comment]
Yes, you are right. But the upstream lib do not support markdown footnote syntax well, so I disabled footnote parsing. Now you can upgrade and have a test.

**Comment by emms007** [comment]
looks clearer like that 👍
