### ISSUE TITLE
[feat] Pin-anchor nicer logo, and breadcrumb direct navigation

### ISSUE THREAD

**Issue by emms007** [vipzhicheng/logseq-plugin-mark-map#55]
Hello,

Thanks again for the great plugin. 
The pin-anchor a is a great way to navigate and would greatly benefit from two changes.

### Changes
1. A nicer pin icon. The current one could be confused with text content. A more visual choice that describe anchor could be the pinpush emoji. It could be "red" when activated and greyed out when available for selection
![image](https://user-images.githubusercontent.com/171033/204770819-eee978a5-555a-4a9c-a6c5-4c47b6866572.png)

3. A way to navigate to the previous level of the tree. Currently it required to go back to the main page level, and makes a big zooming animation with lots of contents displayed. This kind of break the natural flow. Ideally this could be done using a breadcrumb, allowing to switch to another level at minimal click and visual disturbances; 
![image](https://user-images.githubusercontent.com/171033/204771767-785da9eb-a418-4657-ae9b-c732e6632898.png)

###  MD file for demo:
[test%2Fmindmap.md](https://github.com/vipzhicheng/logseq-plugin-mark-map/files/10122137/test.2Fmindmap.md)

**Comment by vipzhicheng** [comment]
I will take your first advice,and change the anchor icon, but for the second one, it's a complicated solution. If you want to go back, you can click right top icons to go back and forward, and you also can trigger these actions by `cmd+[` and `cmd+]`

**Comment by vipzhicheng** [comment]
No. 1 has been released.

**Comment by emms007** [comment]
Thanks!
