### ISSUE TITLE
shortcut ctrl-m conflicts on windows

### ISSUE THREAD

**Issue by ndc33** [vipzhicheng/logseq-plugin-mark-map#58]
Hi, CTRL m on windows is to minimize (a requirement when using full screen mode. Perhaps provide an option to disable all markmap shortcuts?

**Comment by vipzhicheng** [comment]
It's awkward that shortcuts always conflict with System or other plugins. Markmap provides a settings file to adjust shortcuts, the entry is marked in the below screenshot.

![image](https://user-images.githubusercontent.com/1209538/224629972-38500dac-fdff-4fbf-bcea-b66d315d4631.png)

There is no UI for this. please have a try.

**Comment by pasoevi** [comment]
For me, it seems to conflict with its own shortcuts:
![Screenshot 2023-03-19 170516](https://user-images.githubusercontent.com/2624191/226192638-aadc75a7-d5ba-4fcd-acea-41ef040caeeb.png)

As a result, the plugin doesn't activate after installing and doesn't show up in the Plugin toggle menu in the toolbar.

**Comment by vipzhicheng** [comment]
OK, as this issue happened, I want to disable all of the keybindings by default, but let users decide and set them in the settings file. What about this way to change?

**Comment by pasoevi** [comment]
I tried removing all keybindings, and I no longer get the above errors, but the plugin still doesn't work.

I installed the plugin both, on Mac and Windows (I even tried with fresh installation of LogSeq in both, to make sure my config isn't breaking the plugin) and it gives the above errors in both platforms and I cannot make it work even after removing all keybindings.

**Comment by ndc33** [comment]
Hi, just to say I would prefer an option to have NO shortcuts (shortcuts are only of benefit when long time spent immersed in an environment). This package has so many bindings it 'stomps' on everything else.

**Comment by pasoevi** [comment]
Sorry, my bad. The plugin is actually (it is actually awesome!) loading after getting rid of key binding conflicts.
