### ISSUE TITLE
Navigating

### ISSUE THREAD

**Issue by Tafiti** [vipzhicheng/logseq-plugin-mark-map#6]
This is a great tool. 
Is there a way to navigate (either expand or collapse) sibling by sibling? What I can manage so far is navigate step by step. The closest I came was `j` where all siblings are shown. Is there a way to break down what `j` is doing to have a sibling-by-sibling approach? 
May be it is there but I have not found it under the shortcuts. 
I think it would be a good way when presenting information that is sequential and where posting it on the screen all at once may be a less than ideal set up.

**Comment by vipzhicheng** [comment]
For now, there is a FOCUS mode, which you first press `.`, then press `n` and `p` to navigate child sibling map. Please have a try and tell me if it can solve your needs.

By the way, it's hard to implement that showing next sibling, and collapse the previous sibling at the same time. So I am not going to implement this navigation style, but implemented the FOCUS mode instead.

**Comment by Tafiti** [comment]
I have been using FOCUS mode as a hack around the issue. 

You do not have to collapse the previous sibling. Rather, it is to only show siblings one by one as you present them. Basically what `j` is currently doing but instead of showing everything under that sibling at once, you have them show up one by one. 

I admit some situations may require all siblings at once but if this was an option, it would help in progressive presentations. 

Thank you for such a handy tool.

**Comment by vipzhicheng** [comment]
Finally I got what you mean, but sorry, IMO, it's not feasible, because the state of collapse is on the parent node, it controls all children nodes. I did think this idea before, but have no idea how to implement.
