### ISSUE TITLE
logseq 0.9.2 版本里看不到右上角那个小图标了

### ISSUE THREAD

**Issue by lzhga-tx** [vipzhicheng/logseq-plugin-mark-map#61]
logseq 0.9.2 版本里看不到右上角那个小图标了，退回到logseq0.9.1又能看见，是我哪里设置不正确么？

**Comment by aforank** [comment]
+ 1

**Comment by jfarr1978** [comment]
@lzhga-tx - Me too.

**Comment by ifuensan** [comment]
Me too.

**Comment by hello951** [comment]
+1

**Comment by maxmar391** [comment]
free translation of the original post for non-chinese speakers:
I can't see the small icon to access/start markmap in the upper right corner in logseq 0.9.2, but I can see it again when I go back to logseq 0.9.1, is there something wrong with my settings?

+1 from me
I am using Logseq 0.9.3

**Comment by Rhettup** [comment]
+1

**Comment by Gitbreast** [comment]
Same situation. Now there’s no way to open a mind map of a page in macOS.

**Comment by ifuensan** [comment]
Right clic on block, work too.

![image](https://user-images.githubusercontent.com/5514150/233852975-65ebb1c3-f222-4c93-b4ae-f11b5a4378b8.png)

**Comment by lzhga-tx** [comment]
thanks



---原始邮件---
发件人: "Iván ***@***.***&gt;
发送时间: 2023年4月24日(周一) 凌晨0:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vipzhicheng/logseq-plugin-mark-map] logseq 0.9.2 版本里看不到右上角那个小图标了 (Issue #61)




 
Right clic on block, work too.

**Comment by lzhga-tx** [comment]
Right上面一位朋友说可以这样操作:
 clic on block, work too.(在块的小圆点处点击右键，在弹出来的对话框找到markmap，就可以转化为思维导图。经测试是可行的，感谢)
![1682304483103](https://user-images.githubusercontent.com/78894010/233889590-0b578d6a-1f1f-447c-8d97-06f1511024be.jpg)

**Comment by aforank** [comment]
In order to display mark map for the entire page use command palate

Refer this link
https://github.com/logseq/logseq/issues/9289#issuecomment-1531236323

**Comment by vipzhicheng** [comment]
This is a Logseq core bug, involved in v0.9.2 and fixed in v0.9.5 and v0.9.6. Please update Logseq and have a look.

**Comment by lzhga-tx** [comment]
thanks



---原始邮件---
发件人: "Richard ***@***.***&gt;
发送时间: 2023年5月15日(周一) 上午10:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vipzhicheng/logseq-plugin-mark-map] logseq 0.9.2 版本里看不到右上角那个小图标了 (Issue #61)




 
This is a Logseq core bug, involved in v0.9.2 and fixed in v0.9.5 and v0.9.6. Please update Logseq and have a look.
