### ISSUE TITLE
markmap icon in center column not visible 

### ISSUE THREAD

**Issue by acsr** [vipzhicheng/logseq-plugin-mark-map#63]
I use markmap v0.3.17 Logseq 0.9.4 on MacOS Monterey Desktop.

the markmap icon 
![image](https://user-images.githubusercontent.com/400035/236408961-03bf2547-90c7-4a0b-9ec7-b7666bc95db8.png)
is not visible in my UI anymore. It was available before next to the top most block at the right side

The key sequence `ctrl-M ctrl-M` to invoke Markmap view works fine!

I double checked the custom CSS for conflicting tweaks

**Comment by vipzhicheng** [comment]
It's a core bug and fixed in v0.9.6, please upgrade Logseq.

**Comment by acsr** [comment]
THX for the hint, the icon is back. The new icon is much cleaner and not disturbing even when exported. I really like carrots but as icon?
