### ISSUE TITLE
Feature request: Navigate to actual block on page

### ISSUE THREAD

**Issue by bitbonk** [vipzhicheng/logseq-plugin-mark-map#67]
The mind map visualization is e great tool to navigate and explore a block hierarchy on a page. Especially when the page has many blocks it could be a cool way to find a certain block without having to scroll endlessly - sort of like the table of content of the page.

Please allow me to navigate to a certain block back in the page/editor view by clicking on the block/branch on the mind map.

**Comment by vipzhicheng** [comment]
I'm not sure if I understand right, please take a look at the plugin settings, to see if this option can solve your needs.

![image](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/1209538/b7e66529-31ee-42ea-952f-c0bc1fb10953)

You can clock the green icon to go to any block page

**Comment by bitbonk** [comment]
Ah thank you, I didn't known I could do this. That's what I wanted.
Well, almost, once I hit q and exited the mind map mode and had a quick peek at the page, I would like to go back to the mind map mode just at the place where I left it and be able to continue to navigate back and forth. 
Is this possible too?

**Comment by vipzhicheng** [comment]
Yes, there is a shortcut can do this: double `ctrl+m`

**Comment by fanyangto** [comment]
> Ah thank you, I didn't known I could do this. That's what I wanted. Well, almost 😅, once I hit q and exited the mind map mode and had a quick peek at the page, I would like to go back to the mind map mode just at the place where I left it and be able to continue to navigate back and forth. Is this possible too?

I concur with the original post. Yes, the mind map allows navigation on the map. But the original request is to click on a tree node and return back to the logseq editor mode in the selected block location. This way, I can start editing/use the information right away. 

Imagine a case the page is very long (several screens long with many sections). There is a need to navigate quickly to the right section for editing or copy & paste the content. You can not do that on the mind map mode. 

+1 vote. 

Great tool by the way.

**Comment by seal308** [comment]
> But the original request is to click on a tree node and return back to the logseq editor mode in the selected block location.

I think you can already do that?
So if I clicked on this blue highlight:
![blue highlight to get into node](https://i.imgur.com/r1s2ALk.png)

I now jump into the node:

![node](https://i.imgur.com/POJz61T.png)

Now if I press the Escape key or on the screen the x icon on the top right I get the logseq editor on the block:

![after escape key](https://i.imgur.com/L84Wr2S.png)

**Comment by fanyangto** [comment]
> > But the original request is to click on a tree node and return back to the logseq editor mode in the selected block location.
> 
> I think you can already do that? So if I clicked on this blue highlight: ![blue highlight to get into node](https://camo.githubusercontent.com/3410a239d0118f38d9a16021ee6f356ec370264ac4d41788bc160afd142f54f0/68747470733a2f2f692e696d6775722e636f6d2f72317332414c6b2e706e67)
> 
> I now jump into the node:
> 
> ![node](https://camo.githubusercontent.com/6f98cec72edd933ea4d910d8a9f43d85320a030fde6534f74c9719cb63c9868c/68747470733a2f2f692e696d6775722e636f6d2f504f4a7a3631542e706e67)
> 
> Now if I press the Escape key or on the screen the x icon on the top right I get the logseq editor on the block:
> 
> ![after escape key](https://camo.githubusercontent.com/c342667a8a3e2de070af88d0909cc4b9fb4939193f2777faff363708d1f29bed/68747470733a2f2f692e696d6775722e636f6d2f4c3834577232532e706e67)

You are right! Thank you so much. I missed this entirely.
