### ISSUE TITLE
How to install if I don't understand "npm"

### ISSUE THREAD

**Issue by nekodojo** [vipzhicheng/logseq-plugin-mark-map#68]
I have never used or installed npm, nvm or Node.  Since I don't use Node and I don't program in JS in my daily life, there is a good chance I am missing some or all necessary context information.  The install instructions simply say "npm install" and "npm run".

I don't need to clone this repo and make changes locally.  I would like to be able to simply install the plug-in so it works with LogSeq.

I initially tried to install "npm" first with ubuntu apt package manager.  "npm" would install and I was able to use "npm install <github-url> which installed logseq-plugin-mark-map and a lot of dependencies.  After this pretty much any "npm" command I gave told me it was giving up because I don't have a package.json file (in my home dir). Remember, my goal is to simply install the software, not to maintain a project directory for it.

I did a bit more reading and I was able to remove apt's version of npm, and install nvm, and node lts version.  After this npm-install -g <github-url>" works to install logseq-plugin-mark-map as a "global" package. This install gives hundreds of lines like  npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory.  After this I see /home/$USER/.nvm/versions/node/v20.9.0/lib/node_modules/logseq-plugin-mark-map exists but it's a broken link. So my guess is that "global" install won't work for this project or I'm doing it wrong.

If this is already a solved problem and you can point me to a "How to install and run an NPM/node package guide for Dummies" please share the link.  If it solves all my problems I can report back. 

If you don't really wish to support users with an "easy install" and we should all just download the project directory, cd, and run npm from inside there, let me know that too.

In either case you can probably improve the documentation. If I'm able to figure it out I would be happy to submit a PR for modifying the front page README

**Comment by vipzhicheng** [comment]
Sorry for the doc missing. Actually if you are not a developer, you need to install this plugin from Logseq Marketplace, and before you do that, you need to go to advanced settings to enable "developer mode"

![image](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/1209538/7512f923-634e-4d0f-9885-8ae28368f573)

**Comment by seal308** [comment]
> Sorry for the doc missing. Actually if you are not a developer, you need to install this plugin from Logseq Marketplace, and before you do that, you need to go to advanced settings to enable "developer mode"
> 
> ![image](https://private-user-images.githubusercontent.com/1209538/298267204-7512f923-634e-4d0f-9885-8ae28368f573.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTIzMTksIm5iZiI6MTcwNzM5MjAxOSwicGF0aCI6Ii8xMjA5NTM4LzI5ODI2NzIwNC03NTEyZjkyMy02MzRlLTRkMGYtOTg4NS04YWUyODM2OGY1NzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDhUMTEzMzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGUyYTM5ZjVkYTViN2FhNjI3ZWM2OTgxYzMzY2U0MTA1YWQ1YzgxMDliOTdmODNhYzEyNDFhY2M1MTFjYzkwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Lj3meW0WnAh3Dy3qSsrgoKttXz9G7anL5hTLomuZHDk)

I am running linux and I turned on developer mode and installed the plugin from the marketplace and the plugin is not working for me.

**Comment by vipzhicheng** [comment]
@seal308 Which Linux distribution do you use. I am afraid I need to build an env to test your scenario.

**Comment by seal308** [comment]
> @seal308 Which Linux distribution do you use? I am afraid I need to build an environment to test your scenario.

lubuntu
But i also tried it on a windows computer and have the same issue.

**Comment by vipzhicheng** [comment]
Not sure what happened. I tries to install Logseq on Windows. It works.

**Comment by seal308** [comment]
> Not sure what happened. I tries to install Logseq on Windows. It works.

on logseq windows, i have disabled my other plugins, i do not see a mind map icon when i hover:

![no mindmap icon](https://i.imgur.com/XvVJw1j.png)

I do not seem to have the icons like in your screenshots on the plugin page:

![missing icons](https://i.imgur.com/cho39oJ.png)

**Comment by seal308** [comment]
oh I see the issue.
I was expecting to be able to make a mindmap for each block but this plugin seems to only be able to make mindmaps off a page?

![date invocation](https://i.imgur.com/U1YVoKV.png)

![page mindmap](https://i.imgur.com/yUwJwCl.png)

Is there a way to make a mindmap of specific blocks and not an entire page?

**Comment by vipzhicheng** [comment]
For now, there is a way to apply mindmap for specific blocks. You just neet to focus on any block root, and press double ctrl+m. Then you can just render mindmap for the block and it's children.

**Comment by seal308** [comment]
> For now, there is a way to apply mindmap for specific blocks. You just neet to focus on any block root, and press double ctrl+m. Then you can just render mindmap for the block and it's children.

Thanks so much!
