### ISSUE TITLE
新功能请求：增加默认展开层级设置选项

### ISSUE THREAD

**Issue by m3lab-zzl** [vipzhicheng/logseq-plugin-mark-map#70]
对于一个比较复杂的脑图，可能会有五六层甚至更多内容，打开脑图的时候，如果把它们全部展开往往因为内容过多而失去焦点，建议默认展开到三级，从而让框架一目了然，需要更多细节的时候再继续点击节点展开即可。

因此，建议在设置中增加一个默认展开层级的数字下拉框。

另外，如果可以的话，还希望能追加一个快捷操作，比如按住ctrl再点击节点，将同一层级的所有节点全部展开。直接点击节点则只展开该节点的内容。

**Comment by vipzhicheng** [comment]
目前插件的设计逻辑是保持跟Page一样的展开状态。如果不符合你的预期，建议你按一下键盘上的数字 2 或者 3，看看这种方式是否能临时解决你的问题。

后面一个建议挺好，不过我不确定我能为单击和双击绑定不同的行为，因为这个是上游markmap来定义的行为。

另外试试这几个快捷键，试试是否会有不同的导航体验。

![image](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/1209538/7b2506ce-7b15-464a-935e-047f61664a37)
