### ISSUE TITLE
the node click green dot is too small and far away from the actual node

### ISSUE THREAD

**Issue by fanyangto** [vipzhicheng/logseq-plugin-mark-map#71]
I guess this is a feature request.

The green dot to zoom in to a branch is at the front of the node label. But the node itself (for folding/unfolding a branch), is at the end of the label. The label tends to be very long, so the two dots are far apart.  It's counter-intuitive that the operations for the node are so far away from each other.  The green dot is also very small to click on. 

To improve the usability, I suggest instead of the green dot, two alternatives may be better. 

1. single click on the node to fold/unfold. Double click zoom in. 
2. Turn the label/block text into a link, click on the link zooms in. Text is much larger and easier to click.
 
Cheers. This is a great plugin and has a lot of potentials to improve navigation.

**Comment by vipzhicheng** [comment]
Speaking of the usability, I know there is something hard to use. But this plugin is based on a parent mark map JS lib. It's limited. So what I have done is just to use it as much as possible. Some good ideas may not be implemented at the plugin but should in implemented in the parent lib.

1. The dot is too small

Maybe I need to think about how to make zoom operation(let mark map bigger or smaller) easier.

2. The green dot is far away from the branch fold/unfold icon.

This is ok I think. Every block has a green dot to zoom in. and if it has children then it has a branch fold icon.

Yes, the pluginhas a lot of potentials to improve navigation and I was optimizing it as much as I could. Thanks for your great idea.
