### ISSUE TITLE
Mindmap on specific block + its sub-hierarchy (not the entire page)

### ISSUE THREAD

**Issue by petruut** [vipzhicheng/logseq-plugin-mark-map#72]
This is a fantastic plugin. However its use is limited because I'm forced to use it as an all-or-nothing solution on the entire page.

I want to be able to generate a mind map quickly at the level of the blocks (maybe via keyboard shortcut or the right-click menu) - this will allow more targeted + seamless interactions to happen.

**Comment by seal308** [comment]
> This is a fantastic plugin. However its use is limited because I'm forced to use it as an all-or-nothing solution on the entire page.
> 
> I want to be able to generate a mind map quickly at the level of the blocks (maybe via keyboard shortcut or the right-click menu) - this will allow more targeted + seamless interactions to happen.

You should be able to go to a block and get a mindmap just for that block and not a whole page by pressing: Control M Control M:

You can change the shortcuts to something different in General Settings of logseq -> keymap

![change keymap](https://i.imgur.com/o1yvYp1.png)
