### ISSUE TITLE
Weird bug with image elements.

### ISSUE THREAD

**Issue by SumirSeth** [vipzhicheng/logseq-plugin-mark-map#75]
Before the latest update, i was able to click on the image link and it opened beautifully. After the last update, I am unable to click on the image because there is no image. its just blank and fiddling around with settings did not help. 
![image](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/79976481/adb3ca39-5adf-4016-bc81-feb42358af82)
I have uploaded an image for reference, thanks!

**Comment by vipzhicheng** [comment]
Thanks to point me out, it can be reproduced and fixed now, please upgrade the plugin.
