### ISSUE TITLE
switching out of logseq (through a simple command+tab) causes logseq window to become unusable

### ISSUE THREAD

**Issue by jfaleiro** [vipzhicheng/logseq-plugin-mark-map#76]
switching out of logseq (through a simple command+tab) while the markmap preview is on, causes logseq window to become unusable

I can no longer use any window function, window selection is greyed out:

![image](https://github.com/vipzhicheng/logseq-plugin-mark-map/assets/2514594/9d9dc432-d401-4b0f-b143-2bcc01ebe256)

Only way out is to restart logseq.
 
Logseq Version 0.10.7 (81)

**Comment by vipzhicheng** [comment]
What is your OS system?

I can not reproduce this issue on my MacOS.

If you still have this issue, you can try following options.

1. Press the space key to put the map back into the center.
2. Press the q key to exit the markmap preview.
3. There is a button at the left bottom corner, and there is an action menu when you trigger it.
