### ISSUE TITLE
Image only showing up after clicking on the small icon

### ISSUE THREAD

**Issue by jfaleiro** [vipzhicheng/logseq-plugin-mark-map#77]
not sure what is the expected behavior here, are we supposed to see the image on the mindmap itself, or only after clicking on the small icon?

the node with the image is defined by a standard link to a local file:

`![](../assets/Logo_1717084981211_0.png)`

**Comment by vipzhicheng** [comment]
There is an option to control this. Please have a look at the plugin settings. And by default, it just render image as an icon.
