### ISSUE TITLE
在导图内展开大长页节点会回弹到全局视图

### ISSUE THREAD

**Issue by msjsc001** [vipzhicheng/logseq-plugin-mark-map#84]
在导图内每展开大长页的小节点会回弹到全局视图，导致每点开小节点1次就要重找回之前在看的位置，有没有什么办法能取消这种回弹？

**Comment by vipzhicheng** [comment]
![image](https://github.com/user-attachments/assets/20590af9-456f-4bbc-b76c-8525c6d352fa)
试一下这个选项，取消勾选。

**Comment by msjsc001** [comment]
谢谢，没问题了。
